# Generated by Django 2.0.4 on 2018-04-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.CharField(max_length=8, verbose_name='The short url id')),
                ('orig_url', models.TextField(verbose_name='Original url')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
